vich_uploader:
    db_driver: orm

    mappings:
      article_images:
          uri_prefix: '%app.path.article_images%' 
          namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
          upload_destination: '%kernel.project_dir%/public/images/uploads/articles'
          
